execute:Circle11.cpp Rectangle1.cpp  see.cpp Vect.cpp
	g++ -std=c++11 Circle11.cpp Rectangle1.cpp  see.cpp Vect.cpp -lpthread -lGL -lGLU -lglut -lglui

test: Test.cpp TestRecCir.cpp Circle11.cpp Rectangle1.cpp
	g++ -std=c++11 Test.cpp TestRecCir.cpp Circle11.cpp Rectangle1.cpp

clear:
	rm -rf *o execute
